apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuservicedeployment
spec:
  selector:
    matchLabels:
      app: menuservice
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: menuservice
    spec:
      containers:
      - image: us.icr.io/ajmarra/menuservice:1.0
        name: menuservice
        imagePullPolicy: Always
        ports:
        - containerPort: 9002
      restartPolicy: Always
